# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Me' do
  use_frameworks!
        pod 'Alamofire', '4.4.0'
        pod 'SwiftyJSON'
        pod 'QRCodeReader.swift', '~> 7.5.1'
        pod 'QRCode'
end
